# ****************************
# |docname| - CI configuration
# ****************************
# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: BookServer Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BOOK_SERVER_CONFIG: test
      TEST_DBURL: sqlite+aiosqlite:///${{ github.workspace }}/runestone_test.db
      BOOK_PATH: ${{ github.workspace }}/../RunestoneServer/books
      WEB2PY_PATH: ${{ github.workspace }}/../RunestoneServer
    strategy:
      matrix:
        python-version: ['3.8', '3.9']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pre-reqs
      run: |
        mkdir ../RunestoneComponents
        git clone https://github.com/RunestoneInteractive/RunestoneComponents.git ../RunestoneComponents
        git clone https://github.com/RunestoneInteractive/RunestoneServer.git ../RunestoneServer
        pip install -U pip
        pip install poetry
    - name: Install bookserver
      run: |
        # Why are we doing an update here? Updates should be performed by committers, not automatically.
        poetry update
        poetry install
    - name: Run the Pre Commit Check Script
      run: |
        poetry run ./pre_commit_check.py
